package webapp2.domain;

// Generated 12.Mar.2014 15:13:08 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Standalone generated by hbm2java
 */
public class Standalone implements java.io.Serializable {

	private Long id;
	private double amount;
	private Date created;
	private String name;

	public Standalone() {
	}

	public Standalone(double amount) {
		this.amount = amount;
	}

	public Standalone(double amount, Date created, String name) {
		this.amount = amount;
		this.created = created;
		this.name = name;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
